import { Tool, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Tools', icon: 'LayoutGrid' },
  { id: 'models', name: 'LLM Providers', icon: 'Cpu' },
  { id: 'coding', name: 'Coding & App Builders', icon: 'Code' }, // Renamed for clarity
  { id: 'productivity', name: 'Productivity', icon: 'Zap' },
  { id: 'design', name: 'Design & Creative', icon: 'PenTool' },
  { id: 'image', name: 'Image Generation', icon: 'Image' },
  { id: 'video', name: 'Video Generation', icon: 'Video' },
  { id: 'audio', name: 'Music & Audio', icon: 'Music' },
  { id: 'marketing', name: 'Marketing & SEO', icon: 'Megaphone' },
  { id: 'writing', name: 'Writing', icon: 'FileText' },
  { id: 'chat', name: 'Chatbots', icon: 'MessageSquare' },
  { id: 'analytics', name: 'Data & Analytics', icon: 'BarChart' },
  { id: 'automation', name: 'Automation', icon: 'Workflow' },
  { id: 'research', name: 'Research', icon: 'BookOpen' },
  { id: 'education', name: 'Education', icon: 'GraduationCap' },
  { id: 'legal', name: 'Legal', icon: 'Scale' },
  { id: 'health', name: 'Health & Medical', icon: 'Heart' },
  { id: 'finance', name: 'Finance', icon: 'DollarSign' },
  { id: 'security', name: 'Cybersecurity', icon: 'Shield' },
  { id: 'gaming', name: 'Gaming', icon: 'Gamepad2' },
];

export const TOOLS: Tool[] = [
  // --- WEB & APP BUILDERS (New Additions) ---
  {
    id: 'lovable',
    name: 'Lovable',
    shortDescription: 'Turn ideas into fully functional full-stack web apps.',
    fullDescription: 'Lovable (formerly GPT Engineer) allows you to build production-ready full-stack web applications just by describing them. It handles the frontend, backend connection, database, and authentication automatically.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://lovable.dev',
    features: ['Full stack generation', 'Database integration', 'Instant deploy', 'Supabase auth'],
    alternatives: ['bolt', 'v0'],
    tags: ['Web Dev', 'App Builder', 'No-Code']
  },
  {
    id: 'create-xyz',
    name: 'Create.xyz',
    shortDescription: 'Text-to-site builder for tools and mini-apps.',
    fullDescription: 'Create.xyz turns your words into functional components and mini-apps. It is perfect for building internal tools, calculators, dashboards, and interactive widgets using React and Tailwind.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://create.xyz',
    features: ['Component generation', 'React/Tailwind', 'Interactive widgets', 'GPT-4 integration'],
    alternatives: ['v0', 'bolt'],
    tags: ['Web Dev', 'Low-Code', 'Tools']
  },
  {
    id: 'marblism',
    name: 'Marblism',
    shortDescription: 'Generate scalable SaaS platforms from a single prompt.',
    fullDescription: 'Marblism generates a full-stack Next.js SaaS application including database schema, authentication, API endpoints, and frontend pages from a single prompt.',
    category: 'coding',
    pricing: 'Paid',
    websiteUrl: 'https://marblism.com',
    features: ['Full SaaS boilerplate', 'Database schema', 'API generation', 'Stripe integration'],
    alternatives: ['wasp-ai'],
    tags: ['SaaS', 'Web Dev', 'Full Stack']
  },
  {
    id: 'flutterflow',
    name: 'FlutterFlow AI',
    shortDescription: 'Generate native mobile apps with AI.',
    fullDescription: 'FlutterFlow’s AI Gen feature allows you to generate screens, database schemas, and color themes for iOS and Android applications using text prompts.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://flutterflow.io',
    features: ['Mobile app gen', 'Screen generation', 'Schema gen', 'Export to code'],
    alternatives: ['bubble'],
    tags: ['Mobile', 'No-Code', 'Flutter']
  },
  {
    id: 'bubble',
    name: 'Bubble',
    shortDescription: 'No-code web app leader with integrated AI features.',
    fullDescription: 'Bubble allows you to build fully functional web applications without code. Its new AI features help generate layouts, database structures, and dynamic content.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://bubble.io',
    features: ['Full web apps', 'Database management', 'Complex workflows'],
    alternatives: ['flutterflow', 'softr'],
    tags: ['No-Code', 'Web Apps']
  },
  {
    id: 'databutton',
    name: 'Databutton',
    shortDescription: 'AI app builder for data applications.',
    fullDescription: 'Databutton is an AI-powered workspace to build and deploy data apps. It acts as your AI junior developer, writing Python and React code to build dashboards and tools.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://databutton.com',
    features: ['Conversational building', 'Python backend', 'React frontend', 'Data visualization'],
    alternatives: ['streamlit'],
    tags: ['Data Apps', 'Python']
  },
  {
    id: 'softr',
    name: 'Softr AI',
    shortDescription: 'Build client portals and tools from your data.',
    fullDescription: 'Softr lets you turn your Airtable or Google Sheets data into client portals, internal tools, and memberships. The AI app generator builds the entire structure for you.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://softr.io',
    features: ['Text to App', 'Client Portals', 'Data integration'],
    alternatives: ['glide', 'bubble'],
    tags: ['No-Code', 'Business Apps']
  },
  {
    id: 'imagica',
    name: 'Imagica',
    shortDescription: 'Build AI apps without code in minutes.',
    fullDescription: 'Imagica allows you to build AI-powered apps just by describing them. It connects with data sources and allows for complex logic without coding.',
    category: 'coding',
    pricing: 'Waitlist',
    websiteUrl: 'https://get.imagica.ai',
    features: ['No-code', 'AI Logic', 'Instant Publish'],
    alternatives: ['bubble'],
    tags: ['No-Code', 'AI Apps']
  },

  // --- LLM Providers ---
  {
    id: 'gemini',
    name: 'Google Gemini',
    shortDescription: 'Google’s most capable and general multimodal AI model.',
    fullDescription: 'That\'s me! Gemini is built from the ground up to be multimodal, capable of reasoning across text, images, video, audio, and code. It powers Google\'s ecosystem and is designed to be your helpful AI assistant.',
    category: 'models',
    pricing: 'Freemium',
    websiteUrl: 'https://gemini.google.com',
    features: ['Multimodal reasoning', 'Integration with Workspace', '1M+ Context Window', 'Native Audio/Video'],
    alternatives: ['chatgpt', 'claude'],
    tags: ['Google', 'Multimodal', 'Assistant']
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    shortDescription: 'The industry-leading conversational AI by OpenAI.',
    fullDescription: 'ChatGPT is a conversational AI model developed by OpenAI. It is capable of generating human-like text based on context and past conversations. It powers millions of workflows worldwide.',
    category: 'chat',
    pricing: 'Freemium',
    websiteUrl: 'https://chat.openai.com',
    features: ['GPT-4o Model', 'Voice Mode', 'Data Analysis', 'DALL-E Integration'],
    alternatives: ['claude', 'gemini', 'perplexity'],
    tags: ['LLM', 'Chatbot', 'General Purpose']
  },
  {
    id: 'claude',
    name: 'Claude 3.5',
    shortDescription: 'Anthropic’s AI focusing on safety and large context.',
    fullDescription: 'Claude 3.5 Sonnet is known for its nuanced understanding, safety guardrails, and massive context window, making it excellent for analyzing long documents and coding.',
    category: 'models',
    pricing: 'Freemium',
    websiteUrl: 'https://claude.ai',
    features: ['200k+ Context Window', 'Artifacts UI', 'Nuanced writing', 'Coding capabilities'],
    alternatives: ['chatgpt', 'gemini'],
    tags: ['Anthropic', 'Research', 'Coding']
  },
  {
    id: 'grok',
    name: 'Grok',
    shortDescription: 'AI chatbot by xAI with real-time X (Twitter) access.',
    fullDescription: 'Grok is an AI modeled after the Hitchhiker’s Guide to the Galaxy, intended to answer almost anything and, far harder, even suggest what questions to ask. It has real-time knowledge of the world via X.',
    category: 'chat',
    pricing: 'Paid',
    websiteUrl: 'https://x.ai',
    features: ['Real-time X data', 'Witty personality', 'Image generation'],
    alternatives: ['chatgpt', 'perplexity'],
    tags: ['xAI', 'Social', 'Real-time']
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    shortDescription: 'Advanced open-source LLMs focusing on code and math.',
    fullDescription: 'DeepSeek has released powerful open-source models, including DeepSeek-V3 and DeepSeek-R1 (Reasoning), which rival top proprietary models in coding and logic tasks at a fraction of the cost.',
    category: 'models',
    pricing: 'Open Source',
    websiteUrl: 'https://deepseek.com',
    features: ['Reasoning Models', 'Coding prowess', 'Low cost API'],
    alternatives: ['chatgpt', 'claude'],
    tags: ['China', 'Open Source', 'Math']
  },
  {
    id: 'llama-3',
    name: 'Meta Llama 3',
    shortDescription: 'The state-of-the-art open source LLM by Meta.',
    fullDescription: 'Llama 3 is a collection of pre-trained and instruction-tuned generative text models. It sets a new standard for open-source AI performance.',
    category: 'models',
    pricing: 'Open Source',
    websiteUrl: 'https://llama.meta.com',
    features: ['8B, 70B, 400B parameters', 'Open weights', 'High benchmarks'],
    alternatives: ['mistral', 'gemma'],
    tags: ['Meta', 'Open Source', 'LLM']
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    shortDescription: 'Open-weight models and powerful API from France.',
    fullDescription: 'Mistral provides highly efficient open-weight models like Mistral Large and Mixtral via API and Le Chat.',
    category: 'models',
    pricing: 'Freemium',
    websiteUrl: 'https://mistral.ai',
    features: ['Open Weights', 'Efficient Architecture', 'Le Chat interface'],
    alternatives: ['llama-3', 'chatgpt'],
    tags: ['Open Source', 'LLM', 'European']
  },
  {
    id: 'cohere',
    name: 'Cohere',
    shortDescription: 'Enterprise AI platform for search and generation.',
    fullDescription: 'Cohere builds models explicitly for enterprise use cases, featuring strong RAG capabilities and the Command R+ model series.',
    category: 'models',
    pricing: 'Paid',
    websiteUrl: 'https://cohere.com',
    features: ['RAG optimized', 'Enterprise security', 'Embeddings'],
    alternatives: ['openai-enterprise'],
    tags: ['Enterprise', 'RAG']
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    shortDescription: 'AI-powered answer engine with real-time web search.',
    fullDescription: 'Perplexity is a conversational search engine that answers queries using natural language and predictive text, citing sources from the web.',
    category: 'research',
    pricing: 'Freemium',
    websiteUrl: 'https://perplexity.ai',
    features: ['Real-time search', 'Source citations', 'Pro Search mode', 'File upload analysis'],
    alternatives: ['google-search', 'chatgpt'],
    tags: ['Search', 'Research', 'Citations']
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    shortDescription: 'Unified interface for all major LLM APIs.',
    fullDescription: 'OpenRouter provides a standardized API to access the best AI models (GPT-4, Claude 3, Llama 3, Mistral, etc.) at the lowest prices with no monthly commitment.',
    category: 'models',
    pricing: 'Paid',
    websiteUrl: 'https://openrouter.ai',
    features: ['Unified API', 'Pay-as-you-go', 'Model comparison'],
    alternatives: ['together-ai', 'groq'],
    tags: ['API', 'Aggregator', 'Dev']
  },
  {
    id: 'groq',
    name: 'Groq',
    shortDescription: 'The fastest AI inference engine for open models.',
    fullDescription: 'Groq provides LPU (Language Processing Unit) inference technology that delivers near-instantaneous speed for models like Llama 3 and Mixtral.',
    category: 'models',
    pricing: 'Freemium',
    websiteUrl: 'https://groq.com',
    features: ['Lightning fast speed', 'LPU hardware', 'Open models'],
    alternatives: ['openrouter', 'together-ai'],
    tags: ['Hardware', 'Speed', 'API']
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    shortDescription: 'The AI community building the future.',
    fullDescription: 'The hub for AI models, datasets, and demos. It is the GitHub of AI.',
    category: 'models',
    pricing: 'Open Source',
    websiteUrl: 'https://huggingface.co',
    features: ['Model Hub', 'Spaces', 'Datasets', 'Transformers library'],
    alternatives: ['kaggle'],
    tags: ['Community', 'Dev', 'Hub']
  },

  // --- Coding ---
  {
    id: 'cursor',
    name: 'Cursor',
    shortDescription: 'The AI-first code editor tailored for pair programming.',
    fullDescription: 'Cursor is a fork of VS Code that integrates AI deep into the editor, allowing for codebase-wide queries, natural language edits, and smart tab completions.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://cursor.sh',
    features: ['Codebase indexing', 'Natural language edits', 'VS Code extension support', 'Copilot++'],
    alternatives: ['windsurf', 'vscode-copilot'],
    tags: ['IDE', 'Developer', 'Code']
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    shortDescription: 'The first agentic IDE by Codeium.',
    fullDescription: 'Windsurf flows with you. It is an agentic IDE that understands your entire codebase and can perform complex refactors and generation tasks autonomously.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://codeium.com/windsurf',
    features: ['Agentic capabilities', 'Deep context', 'Flow state'],
    alternatives: ['cursor', 'replit'],
    tags: ['IDE', 'Agent', 'Code']
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    shortDescription: 'Your AI pair programmer integrated into your IDE.',
    fullDescription: 'GitHub Copilot uses OpenAI Codex to suggest code and entire functions in real-time, right from your editor.',
    category: 'coding',
    pricing: 'Paid',
    websiteUrl: 'https://github.com/features/copilot',
    features: ['Autocomplete', 'Chat in IDE', 'CLI assistance', 'Enterprise readiness'],
    alternatives: ['cursor', 'codeium'],
    tags: ['Microsoft', 'Developer', 'Code']
  },
  {
    id: 'devin',
    name: 'Devin',
    shortDescription: 'The first fully autonomous AI software engineer.',
    fullDescription: 'Created by Cognition, Devin can plan and execute complex engineering tasks requiring thousands of decisions, learn unfamiliar technologies, and fix bugs.',
    category: 'coding',
    pricing: 'Paid',
    websiteUrl: 'https://www.cognition-labs.com/devin',
    features: ['Autonomous coding', 'Shell access', 'Browser access'],
    alternatives: ['magic', 'opendevin'],
    tags: ['Agent', 'Autonomous', 'Future']
  },
  {
    id: 'replit',
    name: 'Replit AI',
    shortDescription: 'Cloud IDE with integrated AI agent capabilities.',
    fullDescription: 'Replit offers a collaborative browser-based IDE with an AI agent capable of planning and building full-stack applications.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://replit.com',
    features: ['Browser IDE', 'Multiplayer coding', 'AI Agent', 'Instant deployment'],
    alternatives: ['codesandbox', 'cursor'],
    tags: ['Cloud', 'DevOps', 'Agent']
  },
  {
    id: 'v0',
    name: 'v0.dev',
    shortDescription: 'Generative UI system by Vercel.',
    fullDescription: 'v0 allows you to generate copy-and-paste friendly React components using Tailwind CSS and Shadcn UI simply by prompting.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://v0.dev',
    features: ['React generation', 'Tailwind support', 'Interactive preview'],
    alternatives: ['bolt', 'lovo'],
    tags: ['UI', 'Frontend', 'Vercel']
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    shortDescription: 'Prompt, run, and edit full-stack web apps in the browser.',
    fullDescription: 'Bolt is an AI-powered web development agent that allows you to build, run, and deploy full-stack applications directly in the browser without local setup.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://bolt.new',
    features: ['Full stack generation', 'WebContainer technology', 'Instant preview'],
    alternatives: ['replit', 'v0'],
    tags: ['Web Dev', 'Agent', 'StackBlitz']
  },
  {
    id: 'supermaven',
    name: 'Supermaven',
    shortDescription: 'The fastest copilot with a 1-million token context window.',
    fullDescription: 'Supermaven offers incredibly fast code completion with a massive context window, allowing it to understand your entire repo instantly.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://supermaven.com',
    features: ['1M Token Context', 'Low Latency', 'Repo awareness'],
    alternatives: ['codeium', 'copilot'],
    tags: ['Context', 'Fast', 'Autocomplete']
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    shortDescription: 'AI assistant for software developers with privacy focus.',
    fullDescription: 'Tabnine offers context-aware code completion that can run locally or in a private cloud, ensuring your code remains private.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://tabnine.com',
    features: ['Privacy', 'Context-aware', 'Local mode'],
    alternatives: ['copilot', 'codeium'],
    tags: ['Dev', 'Privacy']
  },
  {
    id: 'cody',
    name: 'Cody',
    shortDescription: 'AI coding assistant by Sourcegraph.',
    fullDescription: 'Cody uses Sourcegraph’s code graph to understand your entire codebase and answer questions, write code, and fix bugs.',
    category: 'coding',
    pricing: 'Freemium',
    websiteUrl: 'https://sourcegraph.com/cody',
    features: ['Code graph context', 'IDE extension', 'Enterprise search'],
    alternatives: ['copilot', 'cursor'],
    tags: ['Enterprise', 'Search']
  },

  // --- Image ---
  {
    id: 'midjourney',
    name: 'Midjourney',
    shortDescription: 'High-fidelity artistic image generation.',
    fullDescription: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species. Known for extremely high artistic quality.',
    category: 'image',
    pricing: 'Paid',
    websiteUrl: 'https://midjourney.com',
    features: ['Photorealism', 'Artistic styles', 'Web editor', 'Discord interface'],
    alternatives: ['dalle-3', 'stable-diffusion'],
    tags: ['Art', 'Generative', 'Creative']
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI',
    shortDescription: 'Production-quality image generation for creative assets.',
    fullDescription: 'Leonardo AI provides a suite of tools for creating game assets, art, and concept designs with fine-tuned models.',
    category: 'image',
    pricing: 'Freemium',
    websiteUrl: 'https://leonardo.ai',
    features: ['Game Assets', 'Fine-tuned models', 'Canvas editor'],
    alternatives: ['midjourney', 'scenario'],
    tags: ['Game Dev', 'Assets', 'Creative']
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    shortDescription: 'Advanced text-to-image with superior typography.',
    fullDescription: 'Ideogram solves one of the hardest problems in AI image generation: reliable text rendering within images.',
    category: 'image',
    pricing: 'Freemium',
    websiteUrl: 'https://ideogram.ai',
    features: ['Typography', 'Logo design', 'Prompt adherence'],
    alternatives: ['flux', 'dalle-3'],
    tags: ['Text', 'Design', 'Logos']
  },
  {
    id: 'dalle-3',
    name: 'DALL·E 3',
    shortDescription: 'OpenAI’s image generation model integrated in ChatGPT.',
    fullDescription: 'DALL·E 3 understands significantly more nuance and detail than previous systems, allowing you to easily translate your ideas into exceptionally accurate images.',
    category: 'image',
    pricing: 'Paid',
    websiteUrl: 'https://openai.com/dall-e-3',
    features: ['Prompt adherence', 'ChatGPT integration', 'Safety guardrails'],
    alternatives: ['midjourney', 'flux'],
    tags: ['OpenAI', 'Easy to use']
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    shortDescription: 'Leading open-source image generation model.',
    fullDescription: 'Stability AI’s flagship model. Can be run locally or via API. Known for control, adaptability, and a huge community of fine-tunes.',
    category: 'image',
    pricing: 'Open Source',
    websiteUrl: 'https://stability.ai',
    features: ['Run locally', 'ControlNet support', 'Inpainting/Outpainting'],
    alternatives: ['midjourney', 'dalle-3'],
    tags: ['Open Source', 'Local', 'Flexible']
  },
  {
    id: 'flux',
    name: 'Flux.1',
    shortDescription: 'Next-gen open weights image model by Black Forest Labs.',
    fullDescription: 'Flux provides state-of-the-art image generation with incredible prompt adherence and text rendering capabilities.',
    category: 'image',
    pricing: 'Open Source',
    websiteUrl: 'https://blackforestlabs.ai',
    features: ['Perfect text rendering', 'High detail', 'Open weights'],
    alternatives: ['midjourney', 'ideogram'],
    tags: ['New', 'Trending', 'High Quality']
  },
  {
    id: 'magnific',
    name: 'Magnific AI',
    shortDescription: 'AI upscaler and enhancer that hallucinates details.',
    fullDescription: 'Magnific AI allows you to upscale images to incredible resolutions while adding new details that didn’t exist in the original.',
    category: 'image',
    pricing: 'Paid',
    websiteUrl: 'https://magnific.ai',
    features: ['Upscaling', 'Detail enhancement', 'Style transfer'],
    alternatives: ['topaz'],
    tags: ['Upscale', 'Photography']
  },
  {
    id: 'krea',
    name: 'Krea AI',
    shortDescription: 'Real-time image generation and enhancement.',
    fullDescription: 'Krea offers a real-time canvas where your drawings are instantly turned into AI art, along with powerful enhancement tools.',
    category: 'image',
    pricing: 'Freemium',
    websiteUrl: 'https://krea.ai',
    features: ['Real-time generation', 'Pattern tool', 'Enhancer'],
    alternatives: ['freepik'],
    tags: ['Realtime', 'Design']
  },
  {
    id: 'civitai',
    name: 'Civitai',
    shortDescription: 'The hub for Stable Diffusion models and art.',
    fullDescription: 'The largest community for sharing AI art models, LoRAs, and generated images.',
    category: 'image',
    pricing: 'Free',
    websiteUrl: 'https://civitai.com',
    features: ['Model hosting', 'Image gallery', 'Resource sharing'],
    alternatives: ['huggingface'],
    tags: ['Community', 'Open Source']
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    shortDescription: 'Ecosystem of AI image editing apps.',
    fullDescription: 'Clipdrop by Jasper provides tools like cleanup, background removal, relighting, and upscaling.',
    category: 'image',
    pricing: 'Freemium',
    websiteUrl: 'https://clipdrop.co',
    features: ['Cleanup', 'Relight', 'Remove Background'],
    alternatives: ['canva', 'photoshop'],
    tags: ['Editing', 'Tools']
  },

  // --- Video ---
  {
    id: 'runway',
    name: 'Runway Gen-3',
    shortDescription: 'Advanced video generation and editing suite.',
    fullDescription: 'Runway is an applied AI research company shaping the next era of art, entertainment and human creativity. Their Gen-3 Alpha model creates realistic video from text.',
    category: 'video',
    pricing: 'Paid',
    websiteUrl: 'https://runwayml.com',
    features: ['Text to Video', 'Image to Video', 'Motion Brush', 'Video Inpainting'],
    alternatives: ['pika', 'luma'],
    tags: ['Professional', 'Cinema', 'Creative']
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    shortDescription: 'Idea-to-video platform with sound effects.',
    fullDescription: 'Pika allows you to animate images, modify objects in videos, and generate sound effects (Lip Sync) for your creations.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://pika.art',
    features: ['Lip Sync', 'Sound FX', 'Modify Region'],
    alternatives: ['runway', 'luma'],
    tags: ['Animation', 'Social', 'Creative']
  },
  {
    id: 'kling',
    name: 'Kling AI',
    shortDescription: 'High-quality video generation model from China.',
    fullDescription: 'Kling AI produces highly realistic videos with complex motion, often compared favorably to Sora.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://klingai.com',
    features: ['High realism', 'Long duration', 'Complex motion'],
    alternatives: ['sora', 'runway'],
    tags: ['China', 'Realistic', 'New']
  },
  {
    id: 'sora',
    name: 'Sora',
    shortDescription: 'OpenAI’s highly realistic text-to-video model.',
    fullDescription: 'Sora can create realistic and imaginative scenes from text instructions, featuring complex camera motion and multiple characters.',
    category: 'video',
    pricing: 'Waitlist',
    websiteUrl: 'https://openai.com/sora',
    features: ['60s generation', 'Physics simulation', 'Consistency'],
    alternatives: ['runway', 'kling'],
    tags: ['Hype', 'Realistic', 'Simulation']
  },
  {
    id: 'luma',
    name: 'Luma Dream Machine',
    shortDescription: 'High-quality video generation accessible to everyone.',
    fullDescription: 'Dream Machine is an AI model that makes high quality, realistic videos fast from text and images.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://lumalabs.ai/dream-machine',
    features: ['Fast generation', 'Keyframe control', 'Character consistency'],
    alternatives: ['runway', 'pika'],
    tags: ['3D', 'Video', 'Accessible']
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    shortDescription: 'AI video generation platform for business avatars.',
    fullDescription: 'HeyGen helps you produce studio-quality videos with AI-generated avatars and voices. Perfect for marketing and training.',
    category: 'video',
    pricing: 'Paid',
    websiteUrl: 'https://heygen.com',
    features: ['Custom Avatars', 'Lip Sync', 'Text to Speech', 'Translation'],
    alternatives: ['synthesia', 'd-id'],
    tags: ['Business', 'Avatars', 'Marketing']
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    shortDescription: 'Video generation platform with diverse avatars.',
    fullDescription: 'Create professional AI videos from text in 120+ languages. Great for corporate training and communications.',
    category: 'video',
    pricing: 'Paid',
    websiteUrl: 'https://synthesia.io',
    features: ['Avatars', 'Templates', 'Enterprise security'],
    alternatives: ['heygen'],
    tags: ['Business', 'Training']
  },
  {
    id: 'veed',
    name: 'Veed.io',
    shortDescription: 'Online video editor with AI tools.',
    fullDescription: 'Veed makes video editing simple with AI auto-subtitles, noise removal, and magic cuts.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://veed.io',
    features: ['Auto Subtitles', 'Eye Contact Correction', 'Magic Cut'],
    alternatives: ['descript', 'capcut'],
    tags: ['Editing', 'Social']
  },
  {
    id: 'descript',
    name: 'Descript',
    shortDescription: 'Video editing as easy as a doc.',
    fullDescription: 'Edit video by editing text. Includes powerful AI voice cloning and eye contact correction.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://descript.com',
    features: ['Overdub', 'Studio Sound', 'Text-based editing'],
    alternatives: ['veed', 'premiere'],
    tags: ['Editing', 'Creator']
  },
  {
    id: 'haiper',
    name: 'Haiper',
    shortDescription: 'Perceptual video generation foundation model.',
    fullDescription: 'Haiper is a video generation tool focusing on creativity and high-quality motion.',
    category: 'video',
    pricing: 'Freemium',
    websiteUrl: 'https://haiper.ai',
    features: ['Motion control', 'Artistic styles'],
    alternatives: ['runway', 'pika'],
    tags: ['Creative', 'Video']
  },
  {
    id: 'ltx-studio',
    name: 'LTX Studio',
    shortDescription: 'Holistic AI filmmaking platform.',
    fullDescription: 'LTX Studio by Lightricks allows you to control every aspect of video production, from storyboarding to consistent character generation.',
    category: 'video',
    pricing: 'Waitlist',
    websiteUrl: 'https://ltx.studio',
    features: ['Storyboarding', 'Consistency', 'Director tools'],
    alternatives: ['runway'],
    tags: ['Filmmaking', 'Production']
  },

  // --- Design ---
  {
    id: 'canva',
    name: 'Canva Magic Studio',
    shortDescription: 'All-in-one AI design suite for everyone.',
    fullDescription: 'Canva’s Magic Studio puts the power of AI into every part of the design process, from Magic Eraser to Magic Write and text-to-image.',
    category: 'design',
    pricing: 'Freemium',
    websiteUrl: 'https://canva.com',
    features: ['Magic Switch', 'Magic Media', 'Background Remover', 'Brand Hub'],
    alternatives: ['adobe-firefly', 'figma'],
    tags: ['Social Media', 'Easy', 'Graphics']
  },
  {
    id: 'figma',
    name: 'Figma AI',
    shortDescription: 'AI tools integrated into the leading UI design tool.',
    fullDescription: 'Figma AI helps designers generate layouts, remove backgrounds, and create prototype connections automatically.',
    category: 'design',
    pricing: 'Freemium',
    websiteUrl: 'https://figma.com',
    features: ['Layer renaming', 'Design generation', 'Visual search'],
    alternatives: ['canva', 'sketch'],
    tags: ['UI/UX', 'Professional', 'Vector']
  },
  {
    id: 'framer',
    name: 'Framer',
    shortDescription: 'Generate websites with AI.',
    fullDescription: 'Design and publish your dream site with AI. Type a prompt and get a fully responsive website layout.',
    category: 'design',
    pricing: 'Freemium',
    websiteUrl: 'https://framer.com',
    features: ['Site Gen', 'No-code', 'Animations'],
    alternatives: ['webflow'],
    tags: ['Web', 'Design']
  },
  {
    id: 'looka',
    name: 'Looka',
    shortDescription: 'AI-powered logo and brand identity platform.',
    fullDescription: 'Looka uses AI to help you design a custom logo and build a brand you love in minutes.',
    category: 'design',
    pricing: 'Freemium',
    websiteUrl: 'https://looka.com',
    features: ['Logo maker', 'Brand kit', 'Marketing materials'],
    alternatives: ['canva', 'fiverr'],
    tags: ['Branding', 'Logo']
  },
  {
    id: 'uizard',
    name: 'Uizard',
    shortDescription: 'Design wireframes and prototypes with AI.',
    fullDescription: 'Uizard creates UI designs from text prompts or even hand-drawn sketches.',
    category: 'design',
    pricing: 'Freemium',
    websiteUrl: 'https://uizard.io',
    features: ['Sketch to UI', 'Screenshot to Editable', 'Theme generation'],
    alternatives: ['figma', 'visily'],
    tags: ['UI/UX', 'Prototyping']
  },

  // --- Productivity/Writing ---
  {
    id: 'notion',
    name: 'Notion AI',
    shortDescription: 'Integrated AI writer and database assistant.',
    fullDescription: 'Access the limitless power of AI, right inside Notion. Work faster. Write better. Think bigger. Summarize docs and generate tables.',
    category: 'productivity',
    pricing: 'Paid',
    websiteUrl: 'https://notion.so',
    features: ['Q&A your workspace', 'Summarization', 'Translation', 'Brainstorming'],
    alternatives: ['coda', 'obsidian'],
    tags: ['Docs', 'Knowledge Base', 'Organization']
  },
  {
    id: 'arc',
    name: 'Arc Search',
    shortDescription: 'The browser that browses for you.',
    fullDescription: 'Arc Search uses AI to read multiple pages for you and summarize the answer into a custom web page.',
    category: 'productivity',
    pricing: 'Free',
    websiteUrl: 'https://arc.net',
    features: ['Browse for me', 'Clean UI', 'Mobile app'],
    alternatives: ['perplexity', 'chrome'],
    tags: ['Browser', 'Search', 'Mobile']
  },
  {
    id: 'raycast',
    name: 'Raycast',
    shortDescription: 'Mac spotlight replacement with powerful AI.',
    fullDescription: 'Raycast is a blazingly fast, extendable launcher. Raycast AI lets you control your Mac, write email, and code faster.',
    category: 'productivity',
    pricing: 'Freemium',
    websiteUrl: 'https://raycast.com',
    features: ['System commands', 'AI Chat', 'Extensions'],
    alternatives: ['alfred'],
    tags: ['Mac', 'Productivity', 'Tools']
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    shortDescription: 'AI writing assistance for clear communication.',
    fullDescription: 'Compose bold, clear, mistake-free writing with AI. Checks grammar, tone, and plagiarism.',
    category: 'writing',
    pricing: 'Freemium',
    websiteUrl: 'https://grammarly.com',
    features: ['Tone detector', 'Grammar check', 'Rewrites'],
    alternatives: ['prowritingaid', 'writer'],
    tags: ['Writing', 'Editing']
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    shortDescription: 'AI meeting assistant and note taker.',
    fullDescription: 'Get meeting notes and summaries automatically. Otter joins your Zoom/Meet/Teams calls and records them.',
    category: 'productivity',
    pricing: 'Freemium',
    websiteUrl: 'https://otter.ai',
    features: ['Transcription', 'Summary', 'Chat with meeting'],
    alternatives: ['fireflies', 'fathom'],
    tags: ['Meeting', 'Voice']
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    shortDescription: 'Automate your meeting notes.',
    fullDescription: 'Record, transcribe, and search across your voice conversations. Integrates with CRMs.',
    category: 'productivity',
    pricing: 'Freemium',
    websiteUrl: 'https://fireflies.ai',
    features: ['CRM Integration', 'AskFred', 'Soundbites'],
    alternatives: ['otter'],
    tags: ['Meeting', 'Sales']
  },
  {
    id: 'gamma',
    name: 'Gamma',
    shortDescription: 'Generate presentations with AI.',
    fullDescription: 'A new medium for presenting ideas. Powered by AI. Create beautiful decks, docs, and webpages in seconds.',
    category: 'productivity',
    pricing: 'Freemium',
    websiteUrl: 'https://gamma.app',
    features: ['Decks', 'Webpages', 'One-click polish'],
    alternatives: ['canva', 'tome'],
    tags: ['Office', 'Design']
  },
  {
    id: 'tome',
    name: 'Tome',
    shortDescription: 'AI-powered storytelling format.',
    fullDescription: 'Generative storytelling for presentations and microsites. Turn prompts into full narratives with images.',
    category: 'productivity',
    pricing: 'Freemium',
    websiteUrl: 'https://tome.app',
    features: ['Generative slides', 'DALL-E integration'],
    alternatives: ['gamma'],
    tags: ['Storytelling']
  },

  // --- Marketing ---
  {
    id: 'jasper',
    name: 'Jasper',
    shortDescription: 'AI marketing co-pilot for enterprise content.',
    fullDescription: 'Jasper is an AI copilot for enterprise marketing teams who want better outcomes, not just faster outputs.',
    category: 'marketing',
    pricing: 'Paid',
    websiteUrl: 'https://jasper.ai',
    features: ['Brand Voice', 'Campaign generation', 'SEO mode', 'Team collaboration'],
    alternatives: ['copy-ai', 'writesonic'],
    tags: ['Marketing', 'Enterprise', 'Copywriting']
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    shortDescription: 'GTM AI platform for sales and marketing automation.',
    fullDescription: 'Copy.ai helps GTM teams automate their workflows and generate high-converting copy at scale.',
    category: 'marketing',
    pricing: 'Freemium',
    websiteUrl: 'https://copy.ai',
    features: ['Workflows', 'Chat', 'Scraping', 'Email generation'],
    alternatives: ['jasper', 'hubspot'],
    tags: ['Sales', 'Automation', 'Copy']
  },
  {
    id: 'hubspot',
    name: 'HubSpot AI',
    shortDescription: 'AI tools for CRM and marketing.',
    fullDescription: 'HubSpot integrates AI throughout its CRM platform, offering content assistants, ChatSpot for data queries, and email generation.',
    category: 'marketing',
    pricing: 'Paid',
    websiteUrl: 'https://hubspot.com',
    features: ['ChatSpot', 'Content Asst', 'SEO recommendations'],
    alternatives: ['salesforce'],
    tags: ['CRM', 'Business']
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    shortDescription: 'Generate high-converting ad creatives.',
    fullDescription: 'Artificial Intelligence that generates result-focused ad creatives, social media posts, and texts in seconds.',
    category: 'marketing',
    pricing: 'Paid',
    websiteUrl: 'https://adcreative.ai',
    features: ['Ad generation', 'Scoring', 'Social media'],
    alternatives: ['canva'],
    tags: ['Ads', 'Social']
  },

  // --- Audio ---
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    shortDescription: 'The most realistic AI text-to-speech and voice cloning.',
    fullDescription: 'ElevenLabs is a research company developing the most compelling AI audio software. Known for emotive speech and voice cloning.',
    category: 'audio',
    pricing: 'Freemium',
    websiteUrl: 'https://elevenlabs.io',
    features: ['Voice Cloning', 'Dubbing', 'Sound Effects', 'API'],
    alternatives: ['openai-voice', 'playht'],
    tags: ['TTS', 'Voice', 'Dubbing']
  },
  {
    id: 'suno',
    name: 'Suno',
    shortDescription: 'Make music, vocals, and lyrics from a simple prompt.',
    fullDescription: 'Suno is building a future where anyone can make great music. No instrument needed, just imagination. Generates full songs.',
    category: 'audio',
    pricing: 'Freemium',
    websiteUrl: 'https://suno.com',
    features: ['Full song generation', 'Lyrics generation', 'Style control'],
    alternatives: ['udio', 'soundraw'],
    tags: ['Music', 'Creative', 'Songs']
  },
  {
    id: 'udio',
    name: 'Udio',
    shortDescription: 'High-fidelity music creation platform.',
    fullDescription: 'Udio allows users to create music with high audio fidelity and musicality. Known for its stereo quality and structure.',
    category: 'audio',
    pricing: 'Freemium',
    websiteUrl: 'https://udio.com',
    features: ['High bitrate', 'Extension mode', 'Remixing'],
    alternatives: ['suno'],
    tags: ['Music', 'Production']
  },
  {
    id: 'hume',
    name: 'Hume AI',
    shortDescription: 'Empathic AI that understands voice and emotion.',
    fullDescription: 'Hume provides the Empathic Voice Interface (EVI), the first conversational AI with emotional intelligence.',
    category: 'audio',
    pricing: 'Paid',
    websiteUrl: 'https://hume.ai',
    features: ['Emotion detection', 'Voice interface', 'API'],
    alternatives: ['openai-voice'],
    tags: ['Emotion', 'API', 'Voice']
  },

  // --- Automation/Agents ---
  {
    id: 'zapier',
    name: 'Zapier AI',
    shortDescription: 'Automation workflow platform with AI integrations.',
    fullDescription: 'Zapier connects your apps and services. With AI, it can build Zaps for you via natural language and filter data intelligently.',
    category: 'automation',
    pricing: 'Freemium',
    websiteUrl: 'https://zapier.com',
    features: ['Canvas', 'Copilot for Zaps', 'Interfaces', 'Tables'],
    alternatives: ['make', 'n8n'],
    tags: ['No-Code', 'Workflow', 'Integration']
  },
  {
    id: 'make',
    name: 'Make',
    shortDescription: 'Visual platform for designing complex automated workflows.',
    fullDescription: 'Make (formerly Integromat) lets you design, build, and automate anything from simple tasks to complex workflows visually.',
    category: 'automation',
    pricing: 'Freemium',
    websiteUrl: 'https://make.com',
    features: ['Visual builder', 'AI assistant', '1000+ Apps'],
    alternatives: ['zapier', 'n8n'],
    tags: ['Visual', 'Complex Logic', 'Automation']
  },
  {
    id: 'n8n',
    name: 'n8n',
    shortDescription: 'Fair-code workflow automation tool.',
    fullDescription: 'n8n is an extendable workflow automation tool. With a node-based approach, it lets you connect anything to everything.',
    category: 'automation',
    pricing: 'Open Source',
    websiteUrl: 'https://n8n.io',
    features: ['Self-hostable', 'LangChain nodes', 'Visual editor'],
    alternatives: ['zapier', 'make'],
    tags: ['Dev', 'Self-hosted']
  },
  {
    id: 'crewai',
    name: 'CrewAI',
    shortDescription: 'Framework for orchestrating role-playing AI agents.',
    fullDescription: 'CrewAI allows you to orchestrate role-playing autonomous AI agents. By fostering collaborative intelligence, agents can work together to tackle complex tasks.',
    category: 'automation',
    pricing: 'Open Source',
    websiteUrl: 'https://crewai.com',
    features: ['Role-playing', 'Task delegation', 'Integration with LangChain'],
    alternatives: ['autogen', 'langchain'],
    tags: ['Agents', 'Framework', 'Python']
  },
  {
    id: 'autogen',
    name: 'Microsoft AutoGen',
    shortDescription: 'Framework for multiple LLM agents to converse.',
    fullDescription: 'AutoGen enables the development of LLM applications using multiple agents that can converse with each other to solve tasks.',
    category: 'automation',
    pricing: 'Open Source',
    websiteUrl: 'https://microsoft.github.io/autogen',
    features: ['Multi-agent conversation', 'Code execution', 'Flexible'],
    alternatives: ['crewai'],
    tags: ['Microsoft', 'Agents', 'Research']
  },

  // --- Analytics/Data ---
  {
    id: 'julius',
    name: 'Julius AI',
    shortDescription: 'Your personal AI data analyst.',
    fullDescription: 'Julius analyzes your data. You can chat with your data, create graphs, and build models using simple English.',
    category: 'analytics',
    pricing: 'Paid',
    websiteUrl: 'https://julius.ai',
    features: ['Excel analysis', 'Visualization', 'Statistical modeling'],
    alternatives: ['chatgpt', 'tableau'],
    tags: ['Data Science', 'Visualization', 'Easy']
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    shortDescription: 'Vector database for high-performance AI applications.',
    fullDescription: 'Pinecone makes it easy to provide long-term memory for high-performance AI applications. Managed vector search.',
    category: 'analytics',
    pricing: 'Freemium',
    websiteUrl: 'https://pinecone.io',
    features: ['Vector Search', 'Serverless', 'Low latency'],
    alternatives: ['weaviate', 'qdrant'],
    tags: ['Database', 'Infrastructure', 'RAG']
  },

  // --- Education (New) ---
  {
    id: 'khanmigo',
    name: 'Khanmigo',
    shortDescription: 'AI-powered tutor by Khan Academy.',
    fullDescription: 'Khanmigo is a guide for learners and an assistant for teachers. It doesn\'t just give answers, but guides students to find them.',
    category: 'education',
    pricing: 'Paid',
    websiteUrl: 'https://www.khanacademy.org/khan-labs',
    features: ['Socratic tutoring', 'Lesson planning', 'Coding help'],
    alternatives: ['duolingo', 'socratic'],
    tags: ['Learning', 'Tutor', 'Non-profit']
  },
  {
    id: 'duolingo',
    name: 'Duolingo Max',
    shortDescription: 'Language learning with GPT-4 powered features.',
    fullDescription: 'Duolingo Max includes Roleplay and Explain My Answer features to provide a more immersive learning experience.',
    category: 'education',
    pricing: 'Paid',
    websiteUrl: 'https://duolingo.com',
    features: ['Roleplay', 'Contextual explanations', 'Gamification'],
    alternatives: ['babbel'],
    tags: ['Language', 'Mobile']
  },
  {
    id: 'socratic',
    name: 'Socratic',
    shortDescription: 'Learning app by Google that answers homework questions.',
    fullDescription: 'Socratic uses Google AI to help students understand their school work at a high school and university level.',
    category: 'education',
    pricing: 'Free',
    websiteUrl: 'https://socratic.org',
    features: ['Visual search', 'Step-by-step', 'Multi-subject'],
    alternatives: ['photomath', 'chatgpt'],
    tags: ['Homework', 'Google', 'Mobile']
  },
  {
    id: 'photomath',
    name: 'Photomath',
    shortDescription: 'Scan math problems for instant solutions.',
    fullDescription: 'Photomath reads and solves mathematical problems instantly by using the camera of your mobile device.',
    category: 'education',
    pricing: 'Freemium',
    websiteUrl: 'https://photomath.com',
    features: ['Camera input', 'Step-by-step', 'Graphing'],
    alternatives: ['socratic', 'wolframalpha'],
    tags: ['Math', 'Mobile']
  },

  // --- Legal (New) ---
  {
    id: 'harvey',
    name: 'Harvey',
    shortDescription: 'Generative AI for elite law firms.',
    fullDescription: 'Harvey builds custom LLMs for legal firms to assist with contract analysis, due diligence, and litigation.',
    category: 'legal',
    pricing: 'Paid',
    websiteUrl: 'https://harvey.ai',
    features: ['Legal research', 'Contract analysis', 'Secure'],
    alternatives: ['casetext', 'ironclad'],
    tags: ['Legal', 'Enterprise']
  },
  {
    id: 'casetext',
    name: 'Casetext',
    shortDescription: 'CoCounsel AI legal assistant.',
    fullDescription: 'CoCounsel is the first reliable AI legal assistant, capable of doing document review, deposition preparation, and research.',
    category: 'legal',
    pricing: 'Paid',
    websiteUrl: 'https://casetext.com',
    features: ['CoCounsel', 'Document review', 'Reliability'],
    alternatives: ['harvey', 'lexisplus'],
    tags: ['Legal', 'Research']
  },
  {
    id: 'ironclad',
    name: 'Ironclad AI',
    shortDescription: 'AI for contract lifecycle management.',
    fullDescription: 'Ironclad AI helps legal teams draft, negotiate, and analyze contracts faster using artificial intelligence.',
    category: 'legal',
    pricing: 'Paid',
    websiteUrl: 'https://ironcladapp.com',
    features: ['Contract redlining', 'Clause generation', 'Analytics'],
    alternatives: ['harvey'],
    tags: ['Contracts', 'Business']
  },

  // --- Health (New) ---
  {
    id: 'alphafold',
    name: 'AlphaFold',
    shortDescription: 'AI system that predicts a protein’s 3D structure.',
    fullDescription: 'Developed by Google DeepMind, AlphaFold predicts the 3D structure of proteins from their amino acid sequence, revolutionizing biology.',
    category: 'health',
    pricing: 'Free',
    websiteUrl: 'https://deepmind.google/technologies/alphafold/',
    features: ['Protein folding', 'Scientific breakthrough', 'Database'],
    alternatives: ['rosettafold'],
    tags: ['Biology', 'Science', 'DeepMind']
  },
  {
    id: 'nabla',
    name: 'Nabla',
    shortDescription: 'Ambient AI assistant for clinicians.',
    fullDescription: 'Nabla generates clinical notes automatically from patient consultations, saving doctors hours of documentation time.',
    category: 'health',
    pricing: 'Paid',
    websiteUrl: 'https://nabla.com',
    features: ['Clinical documentation', 'Privacy focused', 'Medical specialized'],
    alternatives: ['abridge', 'nuance'],
    tags: ['Medical', 'Doctors']
  },
  {
    id: 'abridge',
    name: 'Abridge',
    shortDescription: 'Generative AI for medical conversations.',
    fullDescription: 'Abridge structures and summarizes medical conversations for doctors and patients, integrating directly into EMRs.',
    category: 'health',
    pricing: 'Paid',
    websiteUrl: 'https://abridge.com',
    features: ['EMR Integration', 'Audio analysis', 'Clinical notes'],
    alternatives: ['nabla'],
    tags: ['Medical', 'Healthcare']
  },

  // --- Finance (New) ---
  {
    id: 'bloomberg',
    name: 'BloombergGPT',
    shortDescription: 'LLM trained specifically on financial data.',
    fullDescription: 'BloombergGPT is a 50-billion parameter language model trained on a wide range of financial data to support NLP tasks in the financial industry.',
    category: 'finance',
    pricing: 'Paid',
    websiteUrl: 'https://www.bloomberg.com',
    features: ['Financial sentiment', 'Market analysis', 'Domain specific'],
    alternatives: ['finchat'],
    tags: ['Finance', 'Enterprise']
  },
  {
    id: 'cleo',
    name: 'Cleo',
    shortDescription: 'AI financial assistant that roasts your spending.',
    fullDescription: 'Cleo is an AI assistant that helps you budget, save, and build credit with a unique, often humorous personality.',
    category: 'finance',
    pricing: 'Freemium',
    websiteUrl: 'https://meetcleo.com',
    features: ['Budgeting', 'Credit building', 'Chat interface'],
    alternatives: ['mint'],
    tags: ['Personal Finance', 'Consumer']
  },

  // --- Cybersecurity (New) ---
  {
    id: 'darktrace',
    name: 'Darktrace',
    shortDescription: 'Self-learning AI for cyber defense.',
    fullDescription: 'Darktrace uses self-learning AI to detect and autonomously respond to cyber threats in real time across the enterprise.',
    category: 'security',
    pricing: 'Paid',
    websiteUrl: 'https://darktrace.com',
    features: ['Autonomous response', 'Threat detection', 'Enterprise'],
    alternatives: ['crowdstrike'],
    tags: ['Security', 'Enterprise']
  },
  {
    id: 'crowdstrike',
    name: 'Charlotte AI',
    shortDescription: 'Generative AI security analyst by CrowdStrike.',
    fullDescription: 'Charlotte AI allows security teams to ask questions about their security posture and get actionable insights.',
    category: 'security',
    pricing: 'Paid',
    websiteUrl: 'https://crowdstrike.com',
    features: ['Threat hunting', 'Security posture', 'Assistant'],
    alternatives: ['microsoft-security-copilot'],
    tags: ['Security', 'Analyst']
  },

  // --- Gaming (New) ---
  {
    id: 'inworld',
    name: 'Inworld AI',
    shortDescription: 'Engine for smarter NPCs and virtual characters.',
    fullDescription: 'Inworld provides a platform for developers to create realistic, interactive AI characters for games and virtual worlds.',
    category: 'gaming',
    pricing: 'Freemium',
    websiteUrl: 'https://inworld.ai',
    features: ['Character brain', 'Unreal/Unity SDK', 'Contextual memory'],
    alternatives: ['convai'],
    tags: ['Game Dev', 'NPCs']
  },
  {
    id: 'scenario',
    name: 'Scenario',
    shortDescription: 'AI-generated game assets.',
    fullDescription: 'Train and deploy style-consistent AI models for your games. Create textures, props, and concept art.',
    category: 'gaming',
    pricing: 'Paid',
    websiteUrl: 'https://scenario.com',
    features: ['Consistent style', 'Model training', 'Assets'],
    alternatives: ['leonardo'],
    tags: ['Game Dev', 'Assets']
  },
  {
    id: 'rosebud',
    name: 'Rosebud AI',
    shortDescription: 'AI game creation platform.',
    fullDescription: 'Rosebud allows you to build games just by chatting. It generates code, assets, and logic.',
    category: 'gaming',
    pricing: 'Freemium',
    websiteUrl: 'https://rosebud.ai',
    features: ['Chat to Game', 'Asset generation', 'Browser based'],
    alternatives: ['roblox'],
    tags: ['Game Dev', 'No-Code']
  },
   
  // --- Research ---
  {
    id: 'consensus',
    name: 'Consensus',
    shortDescription: 'AI search engine for scientific research.',
    fullDescription: 'Consensus is a search engine that uses AI to find answers in scientific research papers. It summarizes findings and cites sources.',
    category: 'research',
    pricing: 'Freemium',
    websiteUrl: 'https://consensus.app',
    features: ['Paper search', 'Summary', 'Citation extraction'],
    alternatives: ['perplexity', 'scispace'],
    tags: ['Science', 'Academic', 'Reliable']
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    shortDescription: 'AI research assistant by Google grounded in your docs.',
    fullDescription: 'NotebookLM is an AI-first notebook that helps you understand complex information. Upload your sources and it becomes an instant expert on them. Features Audio Overviews.',
    category: 'research',
    pricing: 'Free',
    websiteUrl: 'https://notebooklm.google',
    features: ['Audio Overviews', 'Source grounding', 'Inline citations'],
    alternatives: ['chatgpt', 'obsidian'],
    tags: ['Google', 'Study', 'Notes']
  },
  {
    id: 'scispace',
    name: 'SciSpace',
    shortDescription: 'Platform to understand research papers.',
    fullDescription: 'SciSpace (formerly Typeset) helps you understand research papers better with AI explanations and literature review tools.',
    category: 'research',
    pricing: 'Freemium',
    websiteUrl: 'https://typeset.io',
    features: ['Paper explainer', 'Copilot', 'Literature review'],
    alternatives: ['consensus', 'elicit'],
    tags: ['Academic', 'Science']
  },

  // --- Quick Adds for breadth ---
  { id: 'character-ai', name: 'Character.ai', shortDescription: 'Chat with user-created AI characters.', fullDescription: 'A platform for creating and talking to AI personalities.', category: 'chat', pricing: 'Freemium', websiteUrl: 'https://character.ai', features: ['Personas', 'Voice'], alternatives: ['chai'], tags: ['Fun', 'Social'] },
  { id: 'poe', name: 'Poe', shortDescription: 'Fast AI chat with multiple models.', fullDescription: 'Poe lets you ask questions and get answers from Quora and other AI models.', category: 'chat', pricing: 'Freemium', websiteUrl: 'https://poe.com', features: ['Multi-model', 'Bot creation'], alternatives: ['chatgpt'], tags: ['Aggregator', 'Consumer'] },
  { id: 'beautiful-ai', name: 'Beautiful.ai', shortDescription: 'Presentation software that designs itself.', fullDescription: 'Create beautiful slides quickly with AI.', category: 'productivity', pricing: 'Paid', websiteUrl: 'https://beautiful.ai', features: ['Smart Slides'], alternatives: ['gamma'], tags: ['Office'] },
  { id: 'linear', name: 'Linear', shortDescription: 'Issue tracking with AI insights.', fullDescription: 'Streamline software projects with AI.', category: 'productivity', pricing: 'Freemium', websiteUrl: 'https://linear.app', features: ['Insights', 'Triage'], alternatives: ['jira'], tags: ['Dev', 'Management'] },
  { id: 'quillbot', name: 'Quillbot', shortDescription: 'AI paraphrasing tool.', fullDescription: 'Paraphrase and rewrite text effortlessly.', category: 'writing', pricing: 'Freemium', websiteUrl: 'https://quillbot.com', features: ['Paraphrase', 'Summarize'], alternatives: ['wordtune'], tags: ['Student', 'Writing'] },
  { id: 'weaviate', name: 'Weaviate', shortDescription: 'Open source vector database.', fullDescription: 'Store and search objects and vectors.', category: 'analytics', pricing: 'Open Source', websiteUrl: 'https://weaviate.io', features: ['Hybrid Search'], alternatives: ['pinecone'], tags: ['DB'] },
  { id: 'qdrant', name: 'Qdrant', shortDescription: 'Vector database for the next generation of AI.', fullDescription: 'High-performance vector similarity search.', category: 'analytics', pricing: 'Open Source', websiteUrl: 'https://qdrant.tech', features: ['Rust-based'], alternatives: ['pinecone'], tags: ['DB'] },
  { id: 'wolfram', name: 'WolframAlpha', shortDescription: 'Computational intelligence.', fullDescription: 'Compute answers using AI and built-in knowledge.', category: 'research', pricing: 'Freemium', websiteUrl: 'https://wolframalpha.com', features: ['Math', 'Science'], alternatives: ['chatgpt'], tags: ['Math'] },
  { id: 'meshy', name: 'Meshy', shortDescription: '3D AI generator.', fullDescription: 'Create 3D models from text or images.', category: 'image', pricing: 'Freemium', websiteUrl: 'https://meshy.ai', features: ['Text to 3D'], alternatives: ['lumalabs'], tags: ['3D'] },
  { id: 'rodin', name: 'Rodin', shortDescription: 'Hyper-realistic 3D avatar generation.', fullDescription: 'Generate 3D assets and avatars.', category: 'image', pricing: 'Freemium', websiteUrl: 'https://hyperhuman.deemos.com', features: ['3D Avatars'], alternatives: ['meshy'], tags: ['3D'] },
  { id: 'you', name: 'You.com', shortDescription: 'The AI search engine you control.', fullDescription: 'Search engine with chat and apps.', category: 'research', pricing: 'Freemium', websiteUrl: 'https://you.com', features: ['Search', 'Chat'], alternatives: ['perplexity'], tags: ['Search'] },
  { id: 'brave-leo', name: 'Brave Leo', shortDescription: 'AI assistant in the browser.', fullDescription: 'Private AI built into Brave browser.', category: 'productivity', pricing: 'Free', websiteUrl: 'https://brave.com/leo', features: ['Privacy', 'Summarization'], alternatives: ['arc'], tags: ['Browser'] },
  { id: 'phind', name: 'Phind', shortDescription: 'AI search engine optimized for developers.', fullDescription: 'Phind is an intelligent search engine that provides answers to technical questions with code snippets and documentation links.', category: 'coding', pricing: 'Freemium', websiteUrl: 'https://phind.com', features: ['Developer search', 'VS Code extension', 'Code generation'], alternatives: ['perplexity', 'chatgpt'], tags: ['Search', 'Dev', 'Debug'] },
  { id: 'chatpdf', name: 'ChatPDF', shortDescription: 'Chat with any PDF.', fullDescription: 'Upload a PDF and ask questions about it.', category: 'productivity', pricing: 'Freemium', websiteUrl: 'https://chatpdf.com', features: ['PDF Analysis'], alternatives: ['notebooklm'], tags: ['Docs'] },
  { id: 'clickup', name: 'ClickUp Brain', shortDescription: 'AI knowledge manager.', fullDescription: 'Connects your tasks, docs, and people.', category: 'productivity', pricing: 'Paid', websiteUrl: 'https://clickup.com', features: ['Project Mgmt'], alternatives: ['notion'], tags: ['Productivity'] },
  { id: 'soundraw', name: 'Soundraw', shortDescription: 'AI music generator for creators.', fullDescription: 'Royalty-free music generation.', category: 'audio', pricing: 'Paid', websiteUrl: 'https://soundraw.io', features: ['BGM', 'Royalty Free'], alternatives: ['suno'], tags: ['Music'] },
  { id: 'topaz', name: 'Topaz Video AI', shortDescription: 'Video quality enhancement.', fullDescription: 'Upscale and improve video quality.', category: 'video', pricing: 'Paid', websiteUrl: 'https://topazlabs.com', features: ['Upscale', 'Stabilize'], alternatives: ['capcut'], tags: ['Editing'] },
  { id: 'remini', name: 'Remini', shortDescription: 'Photo enhancer.', fullDescription: 'Restore old photos and enhance quality.', category: 'image', pricing: 'Freemium', websiteUrl: 'https://remini.ai', features: ['Restoration'], alternatives: ['magnific'], tags: ['Photo'] }
];